### ISSUE TITLE
Create Projects Page

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#81]
## TODO 
- [ ] Add new page in the pages folder
- [ ] Create Route `/projects`
- [ ] Serve Projects page in the new route

**Comment by vyasriday** [comment]
Hey would like to take this one @Souvikns

**Comment by Souvikns** [comment]
sure @vyasriday but this will not be an hacktoberfest issue as it has a deadline of  **1st Oct**

**Comment by vyasriday** [comment]
Cool! no problem with that.

**Comment by Souvikns** [comment]
@vyasriday can you give an update on this.

**Comment by vyasriday** [comment]
Will make a PR by EOD.

**Comment by vyasriday** [comment]
@Souvikns addde pr

**Comment by vyasriday** [comment]
@Souvikns It would be really great to label issues accordingly. If it's not part of the hacktoberfest please don't advertise it as such then. Someone like me who is looking for contributing will contribute anyway. But having issues that are clear really helps. :)

**Comment by imabp** [comment]
@vyasriday 
It would be really great, if you have read the guidelines of Hacktoberfest. 

**Contributions from 1st October to 30th October will be taken into account of Hacktoberfest.**

So I hope this clears your doubt, before blaming any one the core members. 

Thankyou : )

**Comment by Souvikns** [comment]
@vyasriday I am extremely sorry for this, I added it by mistake.
